apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  API_KEY: supersecret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/akulatraxas/local-webapp-demo-backend
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
        env:
        - name: AKUDESIRES
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key AKUDESIRES
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8000
