---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
spec:
  encryptedData:
    AKUDESIRES: AgAfkJo+gjEjky67GWKsHgI1+DvVm2815XBjhACarHPLfwxdO6ry/xZ/R7u0RaPi8cf7LMNKoYH0p5GA5IkLAbhTVlo+zwHc5CB2m3WYbzBug33Fq4yfGBi7yl3v6/R1q9iwB4HxHVPd4ENqvPFb0YbTdpC0ZKKaBPPoEQnjnRf4GF0vLXM1QqkNJCYWbpUhqwx0OVz3rcOakDUchp9EIQL7rccQqAnOPHObiCEyh56ho7EUiodqLb9OYRrhLvfrL7I6cG8mjcoNbxoeN9O7bgoizNzt9T7fvzO6C96Y87M9KyNa9P7Ztmg8mVxX3cuzaA6Soz3JMd7fWAN+uNr1W9V5z1KL0G8p8YzNriuV9S1UOObvh3pQyzVWP2vAx6jR+L6Q6oJYMN81ZRRsLjgutuy+bxXS/SG5LtBN2AgMwa/d/nfBfI9tsCvRT1sNVxxQ235sDH/VDxpV7i9eJFPXaYU9nvjT3cCVTXV3dACfbVWfIN9Ei85lZK4GNiRDCwd59/gVKVDt07n6ir8Mgjwm/PL9Q3bTgsVbFOvkQ/roOh1D0cGt9h27zQqb1acFG9Yc3h1cflMtG4CPg8iOwwePPAJ+dmnENF0bf04f93vhrLFr2s7Hov1Iu3I7BXKM7kbUC/ZxycejnA62MaVuQ75JxGJv/Vz12GdhaHEgFWdwKUcQPha8POjRO+zASl5azc91BZV2CRBWemjU0xPsQrf4PbO5Gw==
  template:
    metadata:
      name: backend-secret
