---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: default
spec:
  encryptedData:
    API_KEY: AgBjNDi7Pt+wPqjVCCCWlxAdZQT1wlSh18AhYCkOJZ1pmWluQTduXoICd4gahHtAGv4eXIck5wJMkgwGdNaWoeal4Bb2QSolGS90dvCpluEgC62vpMeg9lZBJlcaPiEtMwmiqqwYTEoBY5AQ69kEiRESlLdpHWJmDMs/nbGPkR09P5TaKMBEMHBEyawcxbNn0XpkUn5C7WuSBTSAWNyufiFSWKhssnTJjDKpgEX7e+v6WFzjZZnX/711ukLB1QWxddnXWljlx7I/lxF4LDyfObUrNkZKXUxkp+xGNtbmNEC4vCb+f5J4kBwzyP+tWaNMEqdFp3kQMT3xArZLWZd1J8yKphI6ABv+2EntkySEbzN4zatSqUc/aVSF4RrhgM/OM37wOu0uIE1GM0jRvTLd/5L/ufZ2j2HPFZam+Zmhsz0ykWzca3wOsRyuox00YgGSHkCrm2jzZopCcU6GMvaPTYnEY/tK1hEi2M1XyiJjG+nXXFWbEReiNEVU2gnXqgfRPurTxDCun0iH/JDFJCUlpO9cJZg9KGSqBCxs3ElrdBvYLjt2+taY/mYbe37qUIaPrtVuNOevXJcGpY/zPe+CdStIbDKy0xF5Aic24udcrsmfleZpPqYEwGWREI8Mxkgwa2nUHA798tCzqzFE9NgRDUsaJASOeuuPioIOWShmZrzLgz5y9mc49VVP7LgDWsLIu7F3N0YagORQtELPrI88jadh
  template:
    metadata:
      name: backend-secret
      namespace: default
