apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webapp-demo

resources:
- ../../base


images:
- name: ghcr.io/akulatraxas/local-webapp-demo-frontend
  newTag: INITIAL
- name: ghcr.io/akulatraxas/local-webapp-demo-backend
  newTag: INITIAL

configMapGenerator:
- literals:
  - APP_ENV=live
  name: backend-config
patches:
- path: ingress-patch.yml
