---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: webapp-demo-live
spec:
  encryptedData:
    AKUDESIRES: AgC9VPsXdkPnVrnddWp/RdiqwanIYnug9iFGaQGm8wkCP+Wk1fHxrfQB7Y5LIgAR+SjOZinJmxEmVwnWYNkKSHKIfAnrDsJihuMmaNPhypz5mNFzv+RHhHgjqHxOhANEsJZu2nUTCEh1zmaq5tqEFCppfgOMN+7QuPcp5+G1ThroH9IwVcXsZ7C7FbuaRDoQP1FYTJfnHpvpUwt99EY532GfP/EahJjwApWBhIgMnO1weemhsox3gTcDMJq9aHBggHTI9tvSyhK+nxkRHFY99JynyWWsD4kvIIjn6ycON0eqzi55aNnHv97sI15NHcaCWGaYXK8ON+qAFPiUuyK/kBj3acynu3OhJ8HyUrnVJK4vQpLlwrPnFbZ0qI7dCRjfUbALHy1VQQ1ZnZX5Pk98Igt+ciZSs33ZitV2ReutSrHZkCKLh6/E/uWbES04wvVkDUnI/9tGod5GKbBmmXav24qKNliokfp7VZ2cr/LSZNFdzyhHt306BHc5DseTK0zykDNYBhHP75tDDEuyAZMpLsG8WGWNbE3Ffih0/5XgpOv7RcrJOHUAkyJK5+Ay1YCf9h3QrOCKnRc1oZpIGg75BnWUZzYuCr43m5JpWWXbiPp2dU4CD9x6pQk1kgmLacEHsxaW6Be7LDpVC/iDobExjjhCsrbtXO/n4iRYqhXpLLM9+bk9LDd1YSaL4qnecO+TwmjN/iCY+qab6HLOH7m4KObHw0ZpE2fXnm/J2/zjuVggjREwCph7hEVvO6RJ8ic=
  template:
    metadata:
      name: backend-secret
      namespace: webapp-demo-live
